#ifndef DISPLAY_H
#define DISPLAY_H

#include "parser.h"
#include "../utils/include/log.h"

#include "raylib.h"

/**
 * @brief Given a RunContainer* generated by the parser, displays all components in raylib
 * 
 * @param container RunContainer* generated by running handleTokenStream()
*/
void displayContainer(RunContainer* container);


#endif